### ISSUE TITLE
Error during refining procedure

### ISSUE THREAD

**Issue by cristian931** [seoklab/GalaxyPepDock#1]
Hi,
I'm running the standalone version of GalaxyPepDock on Ubuntu 16.04, using the following command line:
export GALAXY_HOME=/usr/local/GalaxyPepDock
export EXEC_MPI=/usr/bin/mpiexec
export NSLOTS=20
/usr/local/GalaxyPepDock/bin/GalaxyPepDock.ubuntu1604 -t 1bxl_A_2m04B -p PDB_APO/1bxl.pdb -s FASTA_LIGAND/2m04B.fasta

While this works fine on several other cases, I have this one (and some others) in which the program crashes with the following traceback:
```
Traceback (most recent call last):
File "GalaxyPepDock.py", line 54, in
File "GalaxyPepDock.py", line 44, in main
File "Galaxy/methods/PepDock/libpepdock.py", line 73, in run
File "Galaxy/methods/PepDock/build.py", line 361, in refine_model
File "Galaxy/methods/RefineComplex/librefine.py", line 282, in relaxm
File "Galaxy/galaxy/generate_model/libgenerate_model.py", line 101, in run
File "Galaxy/core/libprotein.py", line 85, in init
File "Galaxy/core/libprotein.py", line 177, in read
File "Galaxy/core/libprotein.py", line 739, in append
ValueError: could not convert string to float: L 8
[55843] Failed to execute script GalaxyPepDock
```
The same exact input results in a successful run on the web-server. I'm attaching the full directory of this run.
Thanks for your help
[1bxl_A_2m04B.tar.gz](https://github.com/seoklab/GalaxyPepDock/files/1788740/1bxl_A_2m04B.tar.gz)

**Comment by seoklab** [comment]
Which MPI environment did you used? GalaxyPepDock supports MPICH hydra (http://www.mpich.org/static/downloads/3.2/hydra-3.2.tar.gz). If you didn't use MPICH hydra to execute jobs in parallel, please download it & try to run again.

**Comment by cristian931** [comment]
Hi,
the problem was exactly that, we were using a different type of mpi environment, now it works perfectly, thanks again for the assistance.
